#
# This codecov.yml is the default configuration for
# all repositories on Codecov. You may adjust the settings
# below in your own codecov.yml in your repository.
#
coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
      app:
        target: 80%
        paths: "app/"
      module:
        target: 80%
        paths:
          - "x/"
          - "!x/**/client/" # ignore client package
    changes: false

comment:
  layout: "reach, diff, files"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "*.md"
  - "*.rst"
  - "contrib/"
  - "docs/"
  - "networks/"
  - "**/*.pb.go"
  - "types/*.pb.go"
  - "tests/*"
  - "tests/**/*"
  - "x/**/*.pb.go"
  - "x/**/test_common.go"